# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard     # Go standard library
        - default      # All other external dependencies
        - localmodule  # This repository's modules

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - usetesting
    - unconvert
    - unparam
    - unused
    - govet
    - testifylint
    - thelper
