# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard     # Go standard library
        - default      # All other external dependencies
        - localmodule  # This repository's modules

linters:
  default: none
  enable:
    - depguard
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - usetesting
    - unconvert
    - unparam
    - unused
    - govet
    - testifylint
    - thelper
  settings:
    depguard:
      rules:
        client:
          files:
            - "**/client/**/*.go"
            - "!$test"
          list-mode: strict
          allow:
            - $gostd
            - github.com/meshcloud/terraform-provider-meshstack/client
        client-test:
          files:
            - "**/client/**/*_test.go"
          list-mode: strict
          allow:
            - $gostd
            - github.com/meshcloud/terraform-provider-meshstack/client
            - github.com/stretchr/testify
        provider:
          files:
            - "!$test"
            - "!**/client/**/*.go"
            - "!**/internal/clientmock/*.go"
          list-mode: strict
          deny:
            - pkg: log # as $gostd is allowed
              desc: Always use 'hclog' or SDK logging
            - pkg: github.com/meshcloud/terraform-provider-meshstack/internal/clientmock
              desc: clientmock package must only be used in tests
          allow:
            - $gostd
            # explicitly specifying 'client' and 'internal' suffixes
            # prevents 'examples' package to be included in non-test files
            - github.com/meshcloud/terraform-provider-meshstack/client
            - github.com/meshcloud/terraform-provider-meshstack/internal
            - github.com/hashicorp/terraform-plugin-framework/
            - github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry
            - github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes # for 'any' value support
            - github.com/hashicorp/terraform-plugin-framework-validators
            - github.com/hashicorp/terraform-plugin-go
            - github.com/hashicorp/terraform-plugin-log
        provider-test:
          files:
            - "$test"
            - "**/internal/clientmock/**/*.go"
            - "!**/internal/types/**/*.go"
            - "!**/client/**/*_test.go"
            - "!**/internal/provider/provider_test.go" # contains common adapters for all tests, using non-testing deps.
          list-mode: strict
          deny:
            - pkg: github.com/meshcloud/terraform-provider-meshstack/client/internal
              desc: Do not use client/internal in provider tests
          allow:
            - $gostd
            - github.com/meshcloud/terraform-provider-meshstack # any packages are included in tests
            - github.com/hashicorp/terraform-plugin-testing
            - github.com/hashicorp/terraform-plugin-framework/diag
            - github.com/stretchr/testify
        types:
          files:
            - "**/internal/types/**/*.go"
            - "!$test"
          list-mode: strict
          deny:
            - pkg: log # as $gostd is allowed
              desc: Always use 'hclog' or SDK logging
          allow:
            - $gostd
            - github.com/meshcloud/terraform-provider-meshstack/client/types # only types should be used from client, if at all!
            - github.com/meshcloud/terraform-provider-meshstack/internal/util/
            - github.com/meshcloud/terraform-provider-meshstack/internal/types/
            - github.com/hashicorp/terraform-plugin-framework/
            - github.com/hashicorp/terraform-plugin-go/tftypes
        types-test:
          files:
            - "**/internal/types/**/*_test.go"
          list-mode: strict
          deny:
            - pkg: log # as $gostd is allowed
              desc: Always use 'hclog' or SDK logging
          allow:
            - $gostd
            - github.com/meshcloud/terraform-provider-meshstack/internal/util/
            - github.com/meshcloud/terraform-provider-meshstack/internal/types/
            - github.com/hashicorp/terraform-plugin-framework/
            - github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes
            - github.com/hashicorp/terraform-plugin-go/tftypes
            - github.com/stretchr/testify
