# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-same-issues: 0

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - copyloopvar
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - usetesting
    - unconvert
    - unparam
    - unused
    - govet
