plugins {
  id 'io.meshcloud.meshstack.go-satellite'
}

satellite {
  acceptance {
    run = 'TestAcc'
    files 'internal/provider/testdata/tf-building-block/**'
    environment TF_ACC: '1',
                TF_ACC_PROVIDER_HOST: 'registry.opentofu.org',
                TF_ACC_TERRAFORM_PATH: onPath('tofu'),
                MESHSTACK_API_KEY: fromBackendConfig('auth.openid.apiKeys.terraform-provider-acceptance.clientId'),
                MESHSTACK_API_SECRET: fromBackendConfig('auth.openid.apiKeys.terraform-provider-acceptance.clientSecret')
  }
}
