version: '3'

dotenv: ['.env']

tasks:
  testacc:
    desc: Run acceptance tests
    env:
      TF_ACC: 1
    cmds:
      - go test ./... -v {{.CLI_ARGS}} -timeout 120m
    
  test:
    desc: Run unit tests only
    cmds:
      - go test ./... -v {{.CLI_ARGS}} -short

  build:
    desc: Build the provider
    cmds:
      - go build {{.CLI_ARGS}} -o terraform-provider-meshstack

  install:
    desc: Install provider locally for testing
    cmds:
      - go install {{.CLI_ARGS}}

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run {{.CLI_ARGS}}

  generate:
    desc: Generate documentation
    cmds:
      - go generate {{.CLI_ARGS}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f terraform-provider-meshstack
      - rm -rf .terraform
      - rm -f .terraform.lock.hcl
